steps:
  # Build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['build',
       '-t', 'gcr.io/$PROJECT_ID/jobtracker-backend:$SHORT_SHA',
       '.']
    dir: 'backend'

  # Push
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push',
       'gcr.io/$PROJECT_ID/jobtracker-backend:$SHORT_SHA']

  # Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      ['run', 'deploy', 'jobtracker-backend',
       '--image', 'gcr.io/$PROJECT_ID/jobtracker-backend:$SHORT_SHA',
       '--region', 'australia-southeast1',
       '--allow-unauthenticated',
       '--set-env-vars',
       'DATABASE_URL=$(DATABASE_URL),WORKOS_API_KEY=$(WORKOS_API_KEY),WORKOS_CLIENT_ID=$(WORKOS_CLIENT_ID),GIN_MODE=release']
