substitutions:
  _PROJECT_ID: ""
  _REGION: ""
  _REPO: ""
  _SERVICE_NAME: ""
  _WORKOS_API_KEY: ""
  _DATABASE_URL: ""
  _WORKOS_CLIENT_ID: ""
  _WORKOS_REDIRECT_URI: ""
  _WORKOS_ISSUER: ""

steps:
  # Step 1: Build Docker image using your Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      [
        'build',
        '-f', 'Dockerfile',
        '-t', '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_SERVICE_NAME}:latest',
        '.'
      ]

  # Step 2: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      [
        'push',
        '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_SERVICE_NAME}:latest'
      ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying ${_SERVICE_NAME}..."
        DEPLOY_OUTPUT=$(gcloud run deploy ${_SERVICE_NAME} \
          --image ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_SERVICE_NAME}:latest \
          --region ${_REGION} \
          --allow-unauthenticated \
          --set-env-vars "WORKOS_API_KEY=${_WORKOS_API_KEY},DATABASE_URL=${_DATABASE_URL},WORKOS_CLIENT_ID=${_WORKOS_CLIENT_ID},WORKOS_REDIRECT_URI=${_WORKOS_REDIRECT_URI},WORKOS_ISSUER=${_WORKOS_ISSUER}" \
          --format='value(status.url)')
        echo "Deployment complete!"
        echo "Cloud Run URL: $DEPLOY_OUTPUT"

images:
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPO}/${_SERVICE_NAME}:latest'
