version: "3.9"

services:
  backend:
    build:
      context: .               
      dockerfile: Dockerfile  
    image: jobtracker-backend  
    ports:
      - "8080:8080"             
    env_file:
      - .env                 
    restart: unless-stopped
