name: Test and Trigger Cloud Build

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      WORKOS_API_KEY: ${{ secrets.WORKOS_API_KEY }}
      WORKOS_CLIENT_ID: ${{ secrets.WORKOS_CLIENT_ID }}
      WORKOS_ISSUER: ${{ secrets.WORKOS_ISSUER }}
      WORKOS_REDIRECT_URI: ${{ secrets.WORKOS_REDIRECT_URI }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      PORT: ${{ secrets.PORT }}
      TEST: ${{ secrets.TEST }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install dependencies
        run: cd backend && go mod tidy

      - name: Build backend
        run: cd backend && go build -v ./...

      - name: Run tests
        run: cd backend && go test ./... -v || echo "⚠️ No tests yet, skipping."

      - name: Lint (optional)
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          cd backend && golangci-lint run || echo "⚠️ Lint warnings ignored for now."

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success()  # only if all tests pass
    steps:
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Trigger Cloud Build deployment
        run: |
          gcloud builds triggers run \
            rmgpgab-jobtracker-backend-australia-southeast1-rupesh110-jouko \
            --region=global
